server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: document-manager-backend

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
